name: Deploy to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry with bumpversion plugin
        run: |
          pipx install poetry
          pipx inject poetry poetry-bumpversion

      - name: Build the package and bump version
        run: |
          poetry version ${{ github.ref_name }}
          poetry build

      - name: Publish to PyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --repository test-pypi